changelog:
  exclude:
    labels:
      - skip-changelog
  categories:
    - title: Security and privacy
      labels:
        - security
        - privacy
    - title: Features
      labels:
        - enhancement
    - title: Fixes
      labels:
        - bug
    - title: Dependencies and maintenance
      labels:
        - dependencies
        - maintenance
    - title: Other changes
      labels:
        - "*"
